name: nba
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  # Core data science
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - sqlalchemy>=2.0.0
  - requests>=2.31.0
  - python-dotenv>=1.0.0
  
  # Machine Learning
  - xgboost>=1.7.0
  - lightgbm>=4.0.0
  - catboost>=1.2.0
  - optuna>=3.2.0
  
  # Feature Store and Model Tracking
  - feast>=0.36.0
  - mlflow>=2.6.0
  
  # Data processing
  - pyarrow>=12.0.0
  - parquet>=1.0.0
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  
  # Development
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - jupytext>=1.10.0
  
  # Testing
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - pytest-mock>=3.11.0
  - pytest-xdist>=3.3.0
  - coverage>=7.2.0
  
  # Additional useful packages
  - ipywidgets
  - nb_conda_kernels
  - black
  - flake8
  - pre-commit
  
  - pip:
    # Local development - shared infrastructure
    - -e ../ml-infrastructure
