name: nba
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - requests>=2.25.0
  - sqlalchemy>=1.4.0
  - python-dotenv>=0.19.0
  - matplotlib>=3.3.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - jupyter>=1.0.0
  - jupytext>=1.10.0
  - pandas>=1.3.0
  - numpy>=1.21.0
  - pip:
    - nba_api>=1.10.0
